PollsProject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('poll/', include('poll.urls')),
    path('admin/', admin.site.urls),
]

poll/urls.py
from django.urls import path

from . import views
app_name = 'poll'
urlpatterns = [
    path('',views.IndexView.as_view(), name='index'),
    path('register/',views.register_page,name='registerpage'),
    path('login/',views.login_page,name='loginpage'),
    path('logout/',views.logout_page,name='logoutpage'),
    path('test', views.test, name='test'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/',views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

poll/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

class Bundle(models.Model):
    class BundleType(models.TextChoices):
        BOOKS = 'BK'
        SOFTWARE = 'SW'
        COMICS = 'CM'
    
    bundle_type = models.CharField(max_length=2,choices= BundleType.choices,default=BundleType.BOOKS,)
    number_of_days = models.IntegerField(default=0)
    title_text = models.CharField(max_length=200)
    description_text = models.CharField(max_length=500)
   # model_pic = models.ImageField(upload_to = 'pic_folder/', default = 'pic_folder/None/no-img.jpg')

poll/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import generic
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages

from .models import Choice, Question
# Create your views here.
def register_page(request):
    form = UserCreationForm()

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("poll:loginpage")

    return render(request,'poll/register.html',{'form':form})
def login_page(request):
    form = AuthenticationForm()

    if request.method == 'POST':
        form = AuthenticationForm(request,data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username,password=password)
            if user is not None:
                login(request, user)
                messages.info(request,'Login in succssfully')
                return redirect("poll:index")
            else:
                messages.error(request,'Login failed. Check username or password')
        else:
            messages.error(request,'Invalid')
    return render(request,'poll/login.html',{'form':form})
def logout_page(request):
    logout(request)
    return redirect("poll:index")
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {
        'latest_question_list': latest_question_list
    }
    return render(request,'poll/index.html',context)
def test(request):
    return HttpResponse("This is a test")
def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request,'poll/detail.html',{'question':question})
def results(request,question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'poll/results.html', {'question': question})

def vote(request,question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request,'poll/detail.html',{'question':question,
        'error_message':"Select an option",})
    else:
        selected_choice.votes +=1
        selected_choice.save()
        return HttpResponseRedirect(reverse('poll:results', args=(question.id,)))

class IndexView(generic.ListView):
    template_name = 'poll/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'poll/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'poll/results.html'

poll/templates/poll/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
		<meta charset="utf-8">
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>{% block title %}{% endblock %}</title>

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
		<link rel="stylesheet" type="text/css" href="{% static 'poll/style.css' %}">
    </head>
    <body>
        
		<nav class="navbar navbar-default" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
				</div>
				<div class="collapse navbar-collapse navbar-ex1-collapse">
					<ul class="nav navbar-nav">
						<li><a href="{% url 'poll:index' %}">Polls</a></li>
					</ul>
					<ul class="nav navbar-nav">
						<li><a href="{% url 'poll:registerpage' %}">Register</a></li>
					</ul>
				</div>
			</div>
		</nav>

		<div class="container">
			{% block main %}{% endblock %}
		</div>

    </body>
</html>

poll/templates/poll/detail.html
{% extends "poll/base.html" %}
{% block main %}
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p class="text-danger"><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'poll:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>
{% endblock %}

poll/templates/poll/index.html
{% extends "poll/base.html" %}
{% block main %}
<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Available Polls</h3>
            </div>
            {% if latest_question_list %} 
            <ul class="list-group">
                {% for question in latest_question_list %}
                <li class="list-group-item">
                    <strong>{{ question.question_text }}</strong>
                    <span class="pull-right">
                        <a href="{% url 'poll:detail' question.id %}" class="btn btn-default btn-xs">Vote</a> &nbsp;
                    </span>
                </li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

poll/templates/poll/login.html
{% extends "poll/base.html" %}
{% block main %}
<div class="row">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Login</h3>
        </div>
    </div>
    <form method ="POST", action="">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn" type="submit">Login</button>>
    </form>
    {% if messages%}
        {% for message in messages %}
        <div class="alert alert-danger">
            {{message}}
        </div>
    {% endfor %}
    {% endif %}
</div>
{% endblock %}

poll/templates/poll/register.html
{% extends "poll/base.html" %}
{% block main %}
<div class="row">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Register</h3>
        </div>
    </div>
    <form method ="POST", action="">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" name="Create Account">
    </form>
    <a href="{% url 'poll:loginpage'%}">Login?</a>
</div>
{% endblock %}

poll/templates/poll/results.html
{% extends "poll/base.html" %}
{% block main %}
<!-- <h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul> -->
<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">{{ question.question_text }}--Results</h3>
            </div>
            <ul class="list-group">
                {% for choice in question.choice_set.all %}
                <li class="list-group-item">
                    <strong>{{ choice.choice_text }}</strong>
                    <span class="pull-right">
                        <b>{{ choice.votes }}</b>
                    </span>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
<a href="{% url 'poll:detail' question.id %}">Vote again?</a>
{% endblock %}